sudo: required
dist: trusty

env:
    - JOB=lintian
    - JOB=test

install:
    # Update to a new version of lintian as the one on trusty is quite old.
    # This also runs apt-get update.
    - ( [[ "$JOB" = lintian ]] && scripts/update_lintian )
    # Install the test suite manually as there is no package for it on trusty.
    - ( [[ "$JOB" = test ]] && git clone https://github.com/sstephenson/bats.git && cd bats && ./install.sh ~/.local )

before_script:
    # The version output of vimpager depends of the tags in the repository so
    # we need to fetch them before running the tests.  Currently all tags are
    # fetched.  TODO: Only fetch the latest tag.
    - git fetch --unshallow --tags

script:
    # The target install-deb also installs the sharutils package that contains
    # uuencode.  Without DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage (which is
    # run by install-deb) would also run the tests.
    - ( [[ "$JOB" = lintian ]] && sudo make install-deb CLEAN_BUILD_DEPS=0 DEB_BUILD_OPTIONS=nocheck )
    # lintian has to be run after make install-deb as it needs the file that
    # are created by the makefile.
    - ( [[ "$JOB" = lintian ]] && lintian --profile debian -i --fail-on-warnings -EvIL +pedantic ../vimpager*.changes )
    - ( [[ "$JOB" = test ]] && make all )
    - ( [[ "$JOB" = test ]] && make test )

# vim: sw=4
