sudo: required
dist: trusty

env:
    - JOB=lintian
    - JOB=test

install:
    # Update to a new version of lintian as the one on trusty is quite old.
    # This also runs apt-get update.
    - if [[ "$JOB" = lintian ]]; then scripts/update_lintian; fi
    # Install the test suite manually as there is no package for it on trusty.
    - if [[ "$JOB" = test ]]; then git clone https://github.com/sstephenson/bats.git && cd bats && ./install.sh ~/.local; fi

before_script:
    # The version output of vimpager depends of the tags in the repository so
    # we need to fetch them before running the tests.  Currently all tags are
    # fetched.  TODO: Only fetch the latest tag.
    - git fetch --unshallow --tags || true

script:
    # The target install-deb also installs the sharutils package that contains
    # uuencode.  Without DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage (which is
    # run by install-deb) would also run the tests.
    - if [[ "$JOB" = lintian ]]; then sudo make install-deb CLEAN_BUILD_DEPS=0 DEB_BUILD_OPTIONS=nocheck; fi
    # lintian has to be run after make install-deb as it needs the file that
    # are created by the makefile.
    - if [[ "$JOB" = lintian ]]; then lintian --profile debian -i --fail-on-warnings -EvIL +pedantic ../vimpager*.changes; fi
    - if [[ "$JOB" = test ]]; then make all; fi
    - if [[ "$JOB" = test ]]; then make test; fi

# vim: sw=4
